from compiler.Compiler import *
import concurrent.futures
import subprocess as sb
from compiler.EggLogCompiler import EggLogCompiler
from utils.ReadDSL import read_string_to_dsl
import sys
import time
import os
import shutil


class PIMFusedCompiler(EggLogCompiler):

    def __init__(self, patterns, src_dsl_list = [], target_dsl_list = [], run_iterations = 10, egg_pkg_path = None, llvm_so_path = None, llvm_flags = [], tests = [],  intrinsics_file = None, hydride_root_path = None, llvm_out_file_name = "llvm.out", prune_patterns = False, parallel = True, skip_axioms = False, extended_dsl_list = []):
        super().__init__(patterns, src_dsl_list = src_dsl_list, target_dsl_list = target_dsl_list, run_iterations = run_iterations,  egg_pkg_path = egg_pkg_path, prune_patterns = prune_patterns, skip_axioms = skip_axioms)
        self.llvm_out_file_name = llvm_out_file_name
        self.llvm_so_path = llvm_so_path
        self.llvm_flags = llvm_flags
        self.output_file_path = "pim_fused_lowering.h"
        self.intrinsics_file = intrinsics_file
        self.hydride_root_path = hydride_root_path
        self.parallel = parallel
        self.input_tests = tests
        self.pool_size = 8
        self.measure_egglog_time = False
        self.egglog_results = []
        self.extended_dsl_list = extended_dsl_list


    def get_reg_vector_type(self, reg):
        return "; (reg {}) <{} x i{}>".format(reg.index, reg.size // reg.precision,  reg.precision)


    def get_rosette_expression_str(self, input_expr ,output_expr, function_name):
        print("GET EXPRESSION STR ")
        expr_str = output_expr.emit_context_expr_string(add_output_type_info = True, use_reg_only = True, hydride_compatible = True)
        regs = get_unique_context_registers(input_expr)
        reg_type_info = [self.get_reg_vector_type(reg) for reg in regs]

        content = [
            "; "+ function_name,
        ]

        content += reg_type_info

        content += [expr_str]

        return "\n".join(content)









    def run_llvm_legalizer(self):
        # Does not actually use LLVM for legalization
        from PIM_API_UTILS import FusedPIMOpLegalizerHalide
        halide_legalizer_gen = FusedPIMOpLegalizerHalide(self.output_file_path, [], self.src_dsl_list + self.extended_dsl_list)

        #defn = halide_legalizer_gen.legalize(test_expr, func_name, [512, 512], [32, 32])

        lowered_progs = []

        for (input_expr, output_expr, function_name) in self.egglog_results:
            regs = get_unique_context_registers(input_expr)
            sizes = [reg.size for reg in regs]
            precs = [reg.precision for reg in regs]
            defn = halide_legalizer_gen.legalize(output_expr, function_name, sizes, precs)
            print(defn)
            lowered_progs.append(defn)


        PIM_HEADER= """
/*
========================================================
This file is automatically generated, DO NOT EDIT!
========================================================
*/
        """

        with open(self.output_file_path, "w+") as CppHeader:
            CppHeader.write(PIM_HEADER+"\n")

            for prog in lowered_progs:
                CppHeader.write(prog+"\n")






    def compile_hydride(self):
        if len(self.input_tests) == 0:
            print("No expressions for MISAAL to compile")
            return

        #assert len(self.input_tests) != 0, "Expected Input tests"
        assert not self.output_file_path is None, "Expected Output file"


        # First preprocess all unique expressions in parallel to
        # overlap compilation of as many expressions as possible,
        # then compile expressions sequentially by memoizing

        PARALLEL = self.parallel

        start_time = time.time()
        unique_expressions = list(set([expr for (name, expr) in self.input_tests]))
        print(len(unique_expressions), "unique expressions to compile")

        def process_unique(i):
            print("PROCESS UNIQUE", i)
            input_expr_str = unique_expressions[i]
            print(input_expr_str)
            input_expr = read_string_to_dsl(input_expr_str, self.src_dsl_list)
            key = input_expr.emit_context_expr_string()
            output_expr = self.compile_expr(input_expr)

        if PARALLEL:
            pool = concurrent.futures.ThreadPoolExecutor(max_workers=self.pool_size)
            for i in range(len(unique_expressions)):
                pool.submit(process_unique, i)
            pool.shutdown(wait=True)
            print("Completed compiling pool...")
        else:
            for i in range(len(unique_expressions)):
                process_unique(i)




        def process_test(i):
            print("PROCESS TEST", i)
            function_name , input_expr_str = self.input_tests[i]
            print(function_name)
            print(input_expr_str)
            input_expr = read_string_to_dsl(input_expr_str, self.src_dsl_list)
            key = input_expr.emit_context_expr_string()

            if self.has_compiled_expr(input_expr):
                print("Already compiled expression!")
                output_expr = self.get_compiled_expr(input_expr)
            else:
                output_expr = self.compile_expr(input_expr)

            output_type_def = (input_expr, output_expr, function_name) #self.get_rosette_expression_str(input_expr ,output_expr, function_name)
            print(output_type_def)

            results[i] = output_type_def



        results = [0] * len(self.input_tests)

        for i in range(len(self.input_tests)):
            process_test(i)




        end_time = time.time()

        elapsed = end_time - start_time

        self.compile_times.append(("EggLogParallel", elapsed))

        print(results)
        self.egglog_results = results


        #with open(self.output_file_path, "w+") as LLVMInputFile:
        #    LLVMInputFile.write("\n".join(results))







    def parse_egglog_output_expr(self, expr_str, num_regs):

        expression_str = expr_str

        for i in range(num_regs):
            expression_str = expression_str.replace("(SYMBV {})".format(i), "(reg (bv {} 8))".format(i))

        print("expression_str", expression_str)
        # Use extended DSL LIST for compilation!
        output_expr = read_string_to_dsl(expression_str, self.extended_dsl_list + self.src_dsl_list)

        return output_expr






