
vec_add_sema =[
            '" (define (typed-folded:vec-add v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %result (bvaddnw slice_v1 slice_v2 iprec sign)) "',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]


vec_sub_sema = [
            '" (define (typed-folded:vec-sub v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %result (bvsubnw slice_v1 slice_v2 iprec sign)) "',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

vec_and_sema = [
        '" (define (typed-folded:vec-bwand v1 v2 iprec isize isign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %result (bvand slice_v1 slice_v2)) "',
        '" %result "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',


    ]

vec_bwor_sema = [
        '" (define (typed-folded:vec-bwor v1 v2 iprec isize isign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %result (bvor slice_v1 slice_v2)) "',
        '" %result "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',


    ]

vec_bwxor_sema = [
        '" (define (typed-folded:vec-bwxor v1 v2 iprec isize isign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %result (bvxor slice_v1 slice_v2)) "',
        '" %result "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',


    ]


vec_mul_sema = [
            '" (define (typed-folded:vec-mul v1 v2 iprec widenprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %widen_slice_v1 (bvsizeext slice_v1 widenprec sign)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %widen_slice_v2 (bvsizeext slice_v2 widenprec sign)) "',
            '" (define prod (bvmul %widen_slice_v1 %widen_slice_v1)) "',
            '" (define %narrow (extract %lastidx1 0 prod)) "',
            '" %narrow "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]


vec_widen_mul_sema = [
        '" (define (typed-folded:vec-widen-mul v1 v2 iprec widenprec isize  sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %widen_slice_v1 (bvsizeext slice_v1 widenprec sign)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %widen_slice_v2 (bvsizeext slice_v2 widenprec sign)) "',
        '" (define %prod (bvmul %widen_slice_v1 %widen_slice_v1)) "',
        '" %prod "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]


vec_div_sema = [
            '" (define (typed-folded:vec-div v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %result (bvdiv slice_v1 slice_v2 sign)) "',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

vec_mod_sema  = [
        '" (define (typed-folded:vec-mod v1 v2 iprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %result (bvrem slice_v1 slice_v2 sign)) "',
        '" %result "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]
vec_max_sema = [
            '" (define (typed-folded:vec-max v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %result (bvmax slice_v1 slice_v2 sign)) "',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

vec_min_sema = [
            '" (define (typed-folded:vec-min v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %result (bvmin slice_v1 slice_v2 sign)) "',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

vec_rnd_shift_right_sema = [
        '" (define (typed-folded:vec-rounding_shift_right v1 v2 iprec widenprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %widen_slice_v1 (bvsizeext slice_v1 widenprec sign)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %widen_slice_v2 (bvsizeext slice_v2 widenprec sign)) "',
        '" (define %max-b-0 (bvmax slice_v2 (bv 0 (bitvector iprec)) sign)) "',
        '" (define %lshift (bvshl (bv 1 (bitvector iprec)) %max-b-0 )) "',
        '" (define %half (bvdiv %lshift (bv 2 (bitvector iprec)) sign)) "',
        '" (define %widen_half_v2 (bvsizeext %half widenprec sign)) "',
        '" (define %sum (bvadd %widen_slice_v1 %widen_half_v2)) "',
        '" (define %rshift (bvshr %sum %widen_slice_v2 sign)) "',
        '" (define %narrow (bvsaturate %rshift widenprec iprec sign)) "',
        '" %narrow "',
        '"  "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]
vec_absd_sema = [
        '" (define (typed-folded:vec-absd v1 v2 iprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define max-v1-v2 (bvmax slice_v1 slice_v2 sign)) "',
        '" (define min-v1-v2 (bvmin slice_v1 slice_v2 sign)) "',
        '" (define %diff (bvsub max-v1-v2 min-v1-v2)) "',
        '" %diff "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]

vec_shr_sema = [
        '" (define (typed-folded:vec-shr v1 v2 iprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %result (bvshr slice_v1 slice_v2 sign)) "',
        '" %result "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]

vec_shl_sema = [
            '" (define (typed-folded:vec-shl v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %result (bvshl slice_v1 slice_v2)) "',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]
vec_eq_sema = [
        '" (define (typed-folded:vec-eq v1 v2 iprec isize isign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %bool (bveq slice_v1 slice_v2)) "',
        '" (define %result (bool-to-bv %bool))"',
        '" %result "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]

vec_lt_sema = [
            '" (define (typed-folded:vec-lt v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %bool (bvlt slice_v1 slice_v2 sign)) "',
            '" (define %result (bool-to-bv %bool))"',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

vec_le_sema = [
            '" (define (typed-folded:vec-le v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %bool (bvle slice_v1 slice_v2 sign)) "',
            '" (define %result (bool-to-bv %bool))"',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]
vec_gt_sema = [
            '" (define (typed-folded:vec-gt v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %bool (bvgt slice_v1 slice_v2 sign)) "',
            '" (define %result (bool-to-bv %bool))"',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]
vec_ge_sema = [
            '" (define (typed-folded:vec-ge v1 v2 iprec isize sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice_v1 (extract %high %iter v1)) "',
            '" (define %lastidx2 (- iprec 1)) "',
            '" (define %high2 (+ %lastidx2 %iter)) "',
            '" (define slice_v2 (extract %high2 %iter v2)) "',
            '" (define %bool (bvge slice_v1 slice_v2 sign)) "',
            '" (define %result (bool-to-bv %bool))"',
            '" %result "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

vec_bw_not_sema = [
        '" (define (typed-folded:vec-bwnot v1 iprec isize isign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %result (bvnot slice_v1)) "',
        '" %result "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]

vec_broadcast_sema = [
        '" (define (typed-folded:broadcast %v1 iprec factor) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 factor 1))]) "',
        '" %v1 "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]


vec_reduce_sema = [
        '" (define (typed-folded:vec-reduce-add reduce-factor v1 iprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%outer (reverse (range 0 isize (* iprec reduce-factor)))]) "',
        '" (apply "',
        '" bvadd "',
        '" (for/list ([%iter (reverse (range 0 reduce-factor 1))]) "',
        '" (define %step (* iprec %iter)) "',
        '" (define %low-offset (+ %outer %step)) "',
        '" (define %lastidx (- iprec 1)) "',
        '" (define %high-idx (+ %low-offset %lastidx)) "',
        '" (define %slice (extract %high-idx %low-offset v1)) "',
        '" %slice "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]

vec_slice_sema = [
        '" (define (typed-folded:slice_vectors %v1 iprec %isize base stride len) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 len 1))]) "',
        '" (define %offset-from-base (* iprec stride)) "',
        '" (define %elem-idx (+ base %iter)) "',
        '" (define %offset-to-base (* %elem-idx iprec)) "',
        '" (define %offset (+ %offset-to-base %offset-from-base)) "',
        '" (define %lastidx (- iprec 1)) "',
        '" (define %high (+ %offset %lastidx)) "',
        '" (define %slice (extract %high %offset %v1)) "',
        '" %slice "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]


vec_concat_sema = [
        '" (define (typed-folded:concat_vectors %v1 %v2 iprec %isize) "',
        '" (define dst "',
        '"(concat %v1 %v2)"'
        '" ) "',
        '" dst "',
        '" ) "',
    ]

cast_extend_sema = [
            '" (define (typed-folded:cast-extend vec iprec isize oprec sign) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice (extract %high %iter vec)) "',
            '" (define %sext (bvsizeext slice oprec sign)) "',
            '" %sext "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

cast_truncate_sema = [
            '" (define (typed-folded:cast-truncate vec iprec isize oprec) "',
            '" (define dst "',
            '" (apply "',
            '" concat "',
            '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
            '" (define %lastidx1 (- iprec 1)) "',
            '" (define %high (+ %lastidx1 %iter)) "',
            '" (define slice (extract %high %iter vec)) "',
            '" (define %offset (- oprec 1)) "',
            '" (define %trunc (extract %offset 0 slice)) "',
            '" %trunc "',
            '" ) "',
            '" ) "',
            '" ) "',
            '" dst "',
            '" ) "',
        ]

cast_saturate_sema = [
        '" (define (typed-folded:vec-saturate vec iprec isize oprec sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice (extract %high %iter vec)) "',
        '" (define %trunc (bvsaturate slice iprec oprec sign)) "',
        '" %trunc "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]


vec_rnd_hlv_add_sema = [
        '" (define (typed-folded:vec-rounding_halving_add v1 v2 iprec widenprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %widen_slice_v1 (bvsizeext slice_v1 widenprec sign)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %widen_slice_v2 (bvsizeext slice_v2 widenprec sign)) "',
        '" (define sum (bvadd %widen_slice_v1 %widen_slice_v1)) "',
        '" (define rounded_sum (bvadd sum (bv 1 (bitvector widenprec)))) "',
        '" (define avg (bvdiv rounded_sum (bv 2 (bitvector widenprec))  sign)) "',
        '" (define %narrow (extract %lastidx1 0 avg)) "',
        '" %narrow "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',



    ]

vec_hlv_add_sema = [
        '" (define (typed-folded:vec-halving_add v1 v2 iprec widenprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %widen_slice_v1 (bvsizeext slice_v1 widenprec sign)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %widen_slice_v2 (bvsizeext slice_v2 widenprec sign)) "',
        '" (define sum (bvadd %widen_slice_v1 %widen_slice_v1)) "',
        '" (define avg (bvdiv sum (bv 2 (bitvector widenprec))  sign)) "',
        '" (define %narrow (extract %lastidx1 0 avg)) "',
        '" %narrow "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',



    ]


vec_rnd_mul_shift_right_sema = [
        '" (define (typed-folded:vec-rounding_mul_shift_right v1 v2 v3 iprec widenprec isize sign) "',
        '" (define dst "',
        '" (apply "',
        '" concat "',
        '" (for/list ([%iter (reverse (range 0 isize iprec))]) "',
        '" (define %lastidx1 (- iprec 1)) "',
        '" (define %high (+ %lastidx1 %iter)) "',
        '" (define slice_v1 (extract %high %iter v1)) "',
        '" (define %widen_slice_v1 (bvsizeext slice_v1 widenprec sign)) "',
        '" (define %lastidx2 (- iprec 1)) "',
        '" (define %high2 (+ %lastidx2 %iter)) "',
        '" (define slice_v2 (extract %high2 %iter v2)) "',
        '" (define %widen_slice_v2 (bvsizeext slice_v2 widenprec sign)) "',
        '" (define %lastidx3 (- iprec 1)) "',
        '" (define %high3 (+ %lastidx3 %iter)) "',
        '" (define slice_v3 (extract %high3 %iter v3)) "',
        '" (define %widen_slice_v3 (bvsizeext slice_v3 widenprec sign)) "',
        '" (define %widen-mul-a-b (bvmul %widen_slice_v1 %widen_slice_v2)) "',
        '" (define %max-q-0 (bvmax %widen_slice_v3 (bv 0 (bitvector widenprec)) sign)) "',
        '" (define %lshift (bvshl (bv 1 (bitvector widenprec)) %max-q-0 )) "',
        '" (define %half (bvdiv %lshift (bv 2 (bitvector widenprec)) sign)) "',
        '" (define %widen_half_v3 (bvsizeext %half (* widenprec 2) sign)) "',
        '" (define %double-widen-mul-a-b (bvsizeext %widen-mul-a-b (* widenprec 2) sign)) "',
        '" (define %sum (bvadd %double-widen-mul-a-b %widen_half_v3)) "',
        '" (define %double-widen-v3 (bvsizeext %widen_slice_v3 (* widenprec 2) sign)) "',
        '" (define %rshift (bvshr %sum %double-widen-v3 sign)) "',
        '" (define %narrow (bvsaturate %rshift (* widenprec 2) widenprec sign)) "',
        '" (define %double-narrow (bvsaturate %narrow widenprec iprec sign)) "',
        '" %double-narrow "',
        '" ) "',
        '" ) "',
        '" ) "',
        '" dst "',
        '" ) "',
    ]
