#include "misaal.h"
#include <tvm/tir/expr.h>

namespace tvm {
namespace tir {
namespace misaal {
    
#define BASIC_VECTORIZABLE_OP(Op) \
bool IsVectorizable(const tir::Op##Node* op){ \
    return op->dtype.is_vector(); \
};

BASIC_VECTORIZABLE_OP(Sub);
BASIC_VECTORIZABLE_OP(Mul);
BASIC_VECTORIZABLE_OP(Div);
BASIC_VECTORIZABLE_OP(Mod);
BASIC_VECTORIZABLE_OP(Min);
BASIC_VECTORIZABLE_OP(Max);
BASIC_VECTORIZABLE_OP(LT);
BASIC_VECTORIZABLE_OP(LE);
BASIC_VECTORIZABLE_OP(GT);
BASIC_VECTORIZABLE_OP(GE);
BASIC_VECTORIZABLE_OP(EQ);
BASIC_VECTORIZABLE_OP(NE);
BASIC_VECTORIZABLE_OP(Or);
BASIC_VECTORIZABLE_OP(And);
BASIC_VECTORIZABLE_OP(Add);

#define DEFINE_NOT_VECTORIZABLE_OP(Op)           \
    bool IsVectorizable(const tir::Op##Node* op){ \
        return false;                            \
    };

DEFINE_NOT_VECTORIZABLE_OP(Var);
DEFINE_NOT_VECTORIZABLE_OP(Cast);
DEFINE_NOT_VECTORIZABLE_OP(IntImm);
DEFINE_NOT_VECTORIZABLE_OP(FloatImm);
DEFINE_NOT_VECTORIZABLE_OP(StringImm);
DEFINE_NOT_VECTORIZABLE_OP(Not);
DEFINE_NOT_VECTORIZABLE_OP(Select);
DEFINE_NOT_VECTORIZABLE_OP(Let);
DEFINE_NOT_VECTORIZABLE_OP(BufferLoad);
DEFINE_NOT_VECTORIZABLE_OP(Call);
DEFINE_NOT_VECTORIZABLE_OP(Ramp);
DEFINE_NOT_VECTORIZABLE_OP(Shuffle);
DEFINE_NOT_VECTORIZABLE_OP(Broadcast);

}
}
}