import unittest
import logging
from utils.PassPipelineUtils import MISAAL_PASS_PIPELINE
from passes.CommutativePass import CommutativePass
from common.DSLParser import parse_dict
from utils.CodeSynthesizerDesc import X86_SYNTH_DESC
import os


class TestCommutativePass(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Set up logging configuration
        CUR_DIR = os.path.dirname(os.path.abspath(__file__))
        log_file = os.path.join(CUR_DIR, "commutative_test.log")
        
        # Configure logging to write to file
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            filename=log_file,
            filemode='w'
        )
        
        # Create a logger for this test
        cls.logger = logging.getLogger('CommutativeTest')

    def setUp(self):
        # Test instruction dictionary containing various x86 instructions
        self.test_instruction_dict = {
            "_mm_add_pi8": {
                "target_instructions": {
                    "_mm_add_pi8": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","-1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm_adds_pi16": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm256_add_epi16": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","16","-1","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.33'}}, {'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                    "_mm_adds_epu16": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_mm_add_epi32": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","-1","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 32,
                        "out_precision": 32,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_m_paddb": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","-1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm256_adds_epu8": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","8","0","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                    "_mm256_adds_epi16": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","16","1","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                    "_m_paddw": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","-1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm_adds_pu16": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm_add_epi16": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","-1","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_mm256_adds_epu16": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","16","0","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                    "_mm_adds_epu8": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_mm512_add_epi16": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","16","-1","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512bw']",
                    },
                    "_mm256_adds_epi8": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","8","1","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                    "_mm_adds_pi8": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm512_add_epi64": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","64","-1","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 64,
                        "out_precision": 64,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512f']",
                    },
                    "_mm_add_pi32": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","-1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 32,
                        "out_precision": 32,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm512_add_epi32": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","32","-1","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 32,
                        "out_precision": 32,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512f']",
                    },
                    "_mm512_adds_epu8": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","8","0","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512bw']",
                    },
                    "_mm256_add_epi64": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","64","-1","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 64,
                        "out_precision": 64,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.33'}}, {'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                    "_mm_add_epi8": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","-1","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_mm_adds_epi16": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","1","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_m_paddsb": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_m_paddd": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","-1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 32,
                        "out_precision": 32,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm_adds_pu8": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm256_add_epi8": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","8","-1","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.33'}}, {'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                    "_mm512_add_epi8": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","8","-1","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512bw']",
                    },
                    "_mm_add_pi16": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","-1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_m_paddusb": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_m_paddusw": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm512_adds_epi16": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","16","1","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512bw']",
                    },
                    "_mm_add_epi64": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","64","-1","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 64,
                        "out_precision": 64,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_m_paddsw": {
                        "args": ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","1","0"],
                        "in_vectsize": 64,
                        "out_vectsize": 64,
                        "lanesize": 64,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['mmx']",
                    },
                    "_mm512_adds_epi8": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","8","1","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512bw']",
                    },
                    "_mm_adds_epi8": {
                        "args": ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","1","0"],
                        "in_vectsize": 128,
                        "out_vectsize": 128,
                        "lanesize": 128,
                        "in_precision": 8,
                        "out_precision": 8,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 1,
                        "Cost": "[{'Skylake': {'l': '1', 't': '0.5'}}]",
                        "SIMD": "True",
                        "Extensions": "['sse2']",
                    },
                    "_mm512_adds_epu16": {
                        "args": ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","16","0","0"],
                        "in_vectsize": 512,
                        "out_vectsize": 512,
                        "lanesize": 512,
                        "in_precision": 16,
                        "out_precision": 16,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": 0,
                        "Cost": "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx512bw']",
                    },
                    "_mm256_add_epi32": {
                        "args": ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","32","-1","0"],
                        "in_vectsize": 256,
                        "out_vectsize": 256,
                        "lanesize": 256,
                        "in_precision": 32,
                        "out_precision": 32,
                        "in_vectsize_index": 2,
                        "out_vectsize_index": 2,
                        "in_lanesize_index": 5,
                        "out_lanesize_index": 3,
                        "in_precision_index": 6,
                        "out_precision_index": 6,
                        "arg_permute_map": [0,1,-1,-1,-1,-1,-1,-1,-1],
                        "Signedness": None,
                        "Cost": "[{'Icelake': {'l': '1', 't': '0.33'}}, {'Skylake': {'l': '1', 't': '0.33'}}]",
                        "SIMD": "True",
                        "Extensions": "['avx2']",
                    },
                },
                "semantics": ['"(define (_mm_add_pi8  a b %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([j0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %lastidx0 (-  %elemsize0  1))"', '"  (define %4 (+  j0.new  %lastidx0))"', '"  (define %5 (extract  %4 j0.new a))"', '"  (define %7 (extract  %4 j0.new b))"', '"  (define %8.ab0 (bvaddnw %5 %7 %elemsize0 %arg0 ))"', '"  %8.ab0"', '" )"', '" )"', '")"', '"(bvpadhighbits  dst %arg1)"', '")"', '""'],
            },
        }

        # Setup working directory
        CUR_DIR = os.path.dirname(os.path.abspath(__file__))
        self.test_working_dir = os.path.join(CUR_DIR, "work")
        self.logger.info(f"Working directory set to: {self.test_working_dir}")

    def test_commutative_properties(self):
        self.logger.info("Starting commutative properties test")
        
        # Create a pass pipeline with the CommutativePass
        pass_pipeline = MISAAL_PASS_PIPELINE(
            [CommutativePass],
            working_directory=self.test_working_dir,
            log_file=os.path.join(self.test_working_dir, "pipeline.log"),
            src_dsl_list=parse_dict(self.test_instruction_dict),
            src_synth_desc=X86_SYNTH_DESC,
            parallelize=False,
            pool=8,
            batch_size=1024,
            target_dsl_list=parse_dict(self.test_instruction_dict),
            target_synth_desc=X86_SYNTH_DESC,
            stop_after_exception=True
        )

        # Run the pass pipeline and check if it succeeds
        result = pass_pipeline.execute_pass_pipeline()
        self.logger.info(f"Pass pipeline execution {'succeeded' if result else 'failed'}")
        self.assertTrue(result, "Commutative pass execution failed")


if __name__ == "__main__":
    unittest.main()
