#============================== Hydride File =================================
#
# Part of the Hydride Compiler Infrastructure.
# <Placeholder for license information>
#
#=============================================================================
#
# Do NOT modify this file. It is automatically generated.
#
#=============================================================================




arm_swizzles = {

          "arm_swizzle_78" : {
            "target_instructions" : {
              "arm_swizzle_78" : {
                  "args" : ["SYMBOLIC_BV_128","64","64","0","64","16","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_76" : {
                  "args" : ["SYMBOLIC_BV_64","32","32","0","32","8","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 32,
                  "lanesize" : 32,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_107" : {
                  "args" : ["SYMBOLIC_BV_128","64","64","0","64","32","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_16" : {
                  "args" : ["SYMBOLIC_BV_128","64","64","0","64","8","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_105" : {
                  "args" : ["SYMBOLIC_BV_64","32","32","0","32","16","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 32,
                  "lanesize" : 32,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_78  v0 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([iterator.0 (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %lastidx0 (-  %elemsize0  1))"', '"  (define %high.offset0 (+  iterator.0  %lastidx0))"', '"  (define %0 (extract  %high.offset0 iterator.0 v0))"', '"  %0"', '" )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg0)"', '")"', '""'],
      },

          "arm_swizzle_51" : {
            "target_instructions" : {
              "arm_swizzle_51" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_32" : {
                  "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32","32","32","0","32","8","8","2","0"],
                  "in_vectsize" : 32,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_97" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","8","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 128,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_204" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","16","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 128,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_93" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","32","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 128,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_257" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","8","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 128,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_259" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","8","8","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_33" : {
                  "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32","32","32","0","32","8","8","2","0"],
                  "in_vectsize" : 32,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_8" : {
                  "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32","32","32","0","32","16","16","2","0"],
                  "in_vectsize" : 32,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_96" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","8","8","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_53" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","8","8","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_206" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","16","16","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_14" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","16","16","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_29" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_10" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","16","16","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_31" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","8","8","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_92" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","32","32","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_51  v0 v1 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([iterator.0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define iterator.0.new.mul (*  iterator.0.new  %arg1))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %high.offset0 (+  iterator.0.new  %lastidx1))"', '"  (define %0 (extract  %high.offset0 iterator.0.new v0))"', '"  (define %1 (extract  %high.offset0 iterator.0.new v1))"', '"(concat %1 %0)"', '" )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg2)"', '")"', '""'],
      },

          "arm_swizzle_48" : {
            "target_instructions" : {
              "arm_swizzle_48" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","96","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_28" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","32","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_95" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","8","8","64","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_205" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","16","16","64","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_49" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","64","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_11" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","16","16","96","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_26" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","96","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_27" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","64","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_258" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","8","8","64","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_91" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","64","32","32","64","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_50" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","8","8","32","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_30" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","8","8","32","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_12" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","16","16","64","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_13" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","32","16","16","32","2","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_9" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","16","16","32","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_52" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","8","8","32","2","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_48  v0 v1 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 %arg3 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([iterator.0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define iterator.0.new.mul (*  iterator.0.new  %arg2))"', '"  (define %low.offset0 (+  iterator.0.new  %arg1))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %high.offset0 (+  %low.offset0  %lastidx1))"', '"  (define %0 (extract  %high.offset0 %low.offset0 v0))"', '"  (define %1 (extract  %high.offset0 %low.offset0 v1))"', '"(concat %1 %0)"', '" )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg3)"', '")"', '""'],
      },

          "arm_swizzle_39" : {
            "target_instructions" : {
              "arm_swizzle_39" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","96","4","16","96","4","24","96","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_44" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","16","4","16","16","4","24","16","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_98" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","8","0","32","8","0","32","8","8","32","4","16","32","4","24","32","4","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 128,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_38" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","112","4","16","112","4","24","112","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_35" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","16","8","0","16","8","0","16","8","8","32","4","16","32","4","24","32","4","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_41" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","64","4","16","64","4","24","64","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_101" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","32","8","0","32","8","0","32","8","8","64","4","16","64","4","24","64","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_34" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","16","8","0","16","8","0","16","8","8","48","4","16","48","4","24","48","4","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_42" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","48","4","16","48","4","24","48","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_100" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","32","8","0","32","8","0","32","8","8","96","4","16","96","4","24","96","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_102" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","32","8","0","32","8","0","32","8","8","32","4","16","32","4","24","32","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_43" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","32","4","16","32","4","24","32","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_46" : {
                  "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32","SYMBOLIC_BV_32","SYMBOLIC_BV_32","32","32","0","16","8","0","16","8","0","16","8","8","16","4","16","16","4","24","16","4","0"],
                  "in_vectsize" : 32,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_36" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","16","8","0","16","8","0","16","8","8","16","4","16","16","4","24","16","4","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_40" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","80","4","16","80","4","24","80","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_39  v0 v1 v2 v3 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %innerlaneoffset1 %innerlanesize1 %elemsize1 %innerlaneoffset2 %innerlanesize2 %elemsize2 %arg0 %arg1 %arg2 %arg3 %arg4 %arg5 %arg6 %arg7 %arg8 %arg9 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (concat "', '"  (apply"', '"  concat"', '"  (for/list ([%iterator2.new (reverse (range %innerlaneoffset2 %innerlanesize2 %elemsize2))])"', '"   (define %low.offset5 (+  %iterator2.new  %arg7))"', '"   (define %lastidx6 (-  %elemsize2  1))"', '"   (define %high.offset6 (+  %low.offset5  %lastidx6))"', '"   (define %3 (extract  %high.offset6 %low.offset5 v3))"', '"   %3"', '"  )"', '"  )"', '"  (apply"', '"  concat"', '"  (for/list ([%iterator1.new (reverse (range %innerlaneoffset1 %innerlanesize1 %elemsize1))])"', '"   (define %low.offset3 (+  %iterator1.new  %arg4))"', '"   (define %lastidx4 (-  %elemsize1  1))"', '"   (define %high.offset4 (+  %low.offset3  %lastidx4))"', '"   (define %2 (extract  %high.offset4 %low.offset3 v2))"', '"   %2"', '"  )"', '"  )"', '"  (apply"', '"  concat"', '"  (for/list ([%iterator0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"   (define %iterator0.new.mul (*  %iterator0.new  %arg2))"', '"   (define %low.offset0 (+  %iterator0.new  %arg1))"', '"   (define %lastidx1 (-  %elemsize0  1))"', '"   (define %high.offset0 (+  %low.offset0  %lastidx1))"', '"   (define %0 (extract  %high.offset0 %low.offset0 v0))"', '"   (define %1 (extract  %high.offset0 %low.offset0 v1))"', '"(concat %1 %0)"', '"  )"', '"  )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg9)"', '")"', '""'],
      },

          "arm_swizzle_19" : {
            "target_instructions" : {
              "arm_swizzle_19" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","32","32","0","32","32","32","0","96","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_20" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","32","32","0","32","32","32","0","64","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_19  v0 v1 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 %arg3 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([%inner.it (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %2 (+  %inner.it  %arg2))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %3 (+  %2  %lastidx1))"', '"  (define %0 (extract  %3 %2 v0))"', '"  (define %1 (extract  %3 %2 v1))"', '"(concat %1 %0)"', '" )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg3)"', '")"', '""'],
      },

          "arm_swizzle_25" : {
            "target_instructions" : {
              "arm_swizzle_25" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","32","32","0","32","32","32","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_21" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","32","32","0","32","32","0","32","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_22" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","32","32","0","32","32","32","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_24" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","32","32","0","32","32","0","32","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_23" : {
                  "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32","32","32","0","32","32","32","0","0"],
                  "in_vectsize" : 32,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_25  v0 v1 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([%inner.it (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %2 (+  %inner.it  %arg1))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %3 (+  %2  %lastidx1))"', '"  (define %0 (extract  %3 %2 v0))"', '"  (define %1 (extract  %3 %2 v1))"', '"(concat %1 %0)"', '" )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg2)"', '")"', '""'],
      },

          "arm_swizzle_293" : {
            "target_instructions" : {
              "arm_swizzle_293" : {
                  "args" : ["SYMBOLIC_BV_128","32","32","0","32","32","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 32,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_1" : {
                  "args" : ["SYMBOLIC_BV_64","32","32","0","32","32","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 32,
                  "lanesize" : 32,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_224" : {
                  "args" : ["SYMBOLIC_BV_128","64","64","0","64","64","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 64,
                  "out_precision" : 64,
                  "in_vectsize_index" : 1,
                  "out_vectsize_index" : 1,
                  "lanesize_index" : 2,
                  "in_precision_index" : 5,
                  "out_precision_index" : 5,
                  "arg_permute_map" : [0,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_293  v0 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([%inner.it (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %1 (+  %inner.it  %arg0))"', '"  (define %lastidx0 (-  %elemsize0  1))"', '"  (define %2 (+  %1  %lastidx0))"', '"  (define %0 (extract  %2 %1 v0))"', '"  %0"', '" )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg1)"', '")"', '""'],
      },

          "arm_swizzle_103" : {
            "target_instructions" : {
              "arm_swizzle_103" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","32","8","0","32","8","0","32","8","8","4","16","4","24","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_37" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","16","8","0","16","8","0","16","8","8","4","16","4","24","4","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_47" : {
                  "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32","SYMBOLIC_BV_32","SYMBOLIC_BV_32","32","32","0","16","8","0","16","8","0","16","8","8","4","16","4","24","4","0"],
                  "in_vectsize" : 32,
                  "out_vectsize" : 64,
                  "lanesize" : 32,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_94" : {
                  "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32","SYMBOLIC_BV_32","SYMBOLIC_BV_32","32","32","0","32","8","0","32","8","0","32","8","8","4","16","4","24","4","0"],
                  "in_vectsize" : 32,
                  "out_vectsize" : 128,
                  "lanesize" : 32,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_45" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","SYMBOLIC_BV_128","64","64","0","16","8","0","16","8","0","16","8","8","4","16","4","24","4","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },

              "arm_swizzle_99" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","32","8","0","32","8","0","32","8","8","4","16","4","24","4","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 128,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 4,
                  "out_vectsize_index" : 4,
                  "lanesize_index" : 5,
                  "in_precision_index" : 14,
                  "out_precision_index" : 14,
                  "arg_permute_map" : [0,1,2,3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : None,
                  "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '1'}}]",
                  "SIMD" : "True",
                  "Extensions" : "['avx2']",
      },
        },
            "semantics" : ['"(define (arm_swizzle_103  v0 v1 v2 v3 %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %innerlaneoffset1 %innerlanesize1 %elemsize1 %innerlaneoffset2 %innerlanesize2 %elemsize2 %arg0 %arg1 %arg2 %arg3 %arg4 %arg5 %arg6 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (concat "', '"  (apply"', '"  concat"', '"  (for/list ([%iterator2.new (reverse (range %innerlaneoffset2 %innerlanesize2 %elemsize2))])"', '"   (define %lastidx6 (-  %elemsize2  1))"', '"   (define %high.offset6 (+  %iterator2.new  %lastidx6))"', '"   (define %3 (extract  %high.offset6 %iterator2.new v3))"', '"   %3"', '"  )"', '"  )"', '"  (apply"', '"  concat"', '"  (for/list ([%iterator1.new (reverse (range %innerlaneoffset1 %innerlanesize1 %elemsize1))])"', '"   (define %lastidx4 (-  %elemsize1  1))"', '"   (define %high.offset4 (+  %iterator1.new  %lastidx4))"', '"   (define %2 (extract  %high.offset4 %iterator1.new v2))"', '"   %2"', '"  )"', '"  )"', '"  (apply"', '"  concat"', '"  (for/list ([%iterator0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"   (define %iterator0.new.mul (*  %iterator0.new  %arg1))"', '"   (define %lastidx1 (-  %elemsize0  1))"', '"   (define %high.offset0 (+  %iterator0.new  %lastidx1))"', '"   (define %0 (extract  %high.offset0 %iterator0.new v0))"', '"   (define %1 (extract  %high.offset0 %iterator0.new v1))"', '"(concat %1 %0)"', '"  )"', '"  )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg6)"', '")"', '""'],
      },
        }
