integer_arith_sema_dict = {
    "DIV" : {
        "target_instructions" : {
            "DIV" : {
                "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32"],
                "in_vectsize" : 32,
                "out_vectsize" : 32,
                "lanesize" : 32,
                "in_precision" : 32,
                "out_precision" : 32,
                "in_vectsize_index" : None,
                "out_vectsize_index" : None,
                "in_lanesize_index" : None,
                "out_lanesize_index" : None,
                "in_precision_index" : None,
                "out_precision_index" : None,
                "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
                "Signedness" : 1,
                "Cost" : "None",
                "SIMD" : "True",
                "Extensions" : "['integer_arith']",
            },
        },
        "semantics" : ['"(define (DIV  a b )"','"(/ a b)"'  ,'")"', '""'],
    },

    "ADD" : {
        "target_instructions" : {
            "ADD" : {
                "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32"],
                "in_vectsize" : 32,
                "out_vectsize" : 32,
                "lanesize" : 32,
                "in_precision" : 32,
                "out_precision" : 32,
                "in_vectsize_index" : None,
                "out_vectsize_index" : None,
                "in_lanesize_index" : None,
                "out_lanesize_index" : None,
                "in_precision_index" : None,
                "out_precision_index" : None,
                "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
                "Signedness" : 1,
                "Cost" : "None",
                "SIMD" : "True",
                "Extensions" : "['integer_arith']",
            },
        },
        "semantics" : ['"(define (ADD  a b )"','"(+ a b)"'  ,'")"', '""'],
    },

    "SUB" : {
        "target_instructions" : {
            "SUB" : {
                "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32"],
                "in_vectsize" : 32,
                "out_vectsize" : 32,
                "lanesize" : 32,
                "in_precision" : 32,
                "out_precision" : 32,
                "in_vectsize_index" : None,
                "out_vectsize_index" : None,
                "in_lanesize_index" : None,
                "out_lanesize_index" : None,
                "in_precision_index" : None,
                "out_precision_index" : None,
                "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
                "Signedness" : 1,
                "Cost" : "None",
                "SIMD" : "True",
                "Extensions" : "['integer_arith']",
            },
        },
        "semantics" : ['"(define (SUB  a b )"','"(- a b)"'  ,'")"', '""'],
    },

    "MUL" : {
        "target_instructions" : {
            "MUL" : {
                "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32"],
                "in_vectsize" : 32,
                "out_vectsize" : 32,
                "lanesize" : 32,
                "in_precision" : 32,
                "out_precision" : 32,
                "in_vectsize_index" : None,
                "out_vectsize_index" : None,
                "in_lanesize_index" : None,
                "out_lanesize_index" : None,
                "in_precision_index" : None,
                "out_precision_index" : None,
                "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
                "Signedness" : 1,
                "Cost" : "None",
                "SIMD" : "True",
                "Extensions" : "['integer_arith']",
            },
        },
        "semantics" : ['"(define (MUL  a b )"','"(* a b)"'  ,'")"', '""'],
    },

    "MOD" : {
        "target_instructions" : {
            "MOD" : {
                "args" : ["SYMBOLIC_BV_32","SYMBOLIC_BV_32"],
                "in_vectsize" : 32,
                "out_vectsize" : 32,
                "lanesize" : 32,
                "in_precision" : 32,
                "out_precision" : 32,
                "in_vectsize_index" : None,
                "out_vectsize_index" : None,
                "in_lanesize_index" : None,
                "out_lanesize_index" : None,
                "in_precision_index" : None,
                "out_precision_index" : None,
                "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
                "Signedness" : 1,
                "Cost" : "None",
                "SIMD" : "True",
                "Extensions" : "['integer_arith']",
            },
        },
        "semantics" : ['"(define (MOD  a b )"','"(remainder a b)"'  ,'")"', '""'],
    },

    "SCALAR" : {
        "target_instructions" : {
            "SCALAR" : {
                "args" : ["SYMBOLIC_BV_32"],
                "in_vectsize" : 32,
                "out_vectsize" : 32,
                "lanesize" : 32,
                "in_precision" : 32,
                "out_precision" : 32,
                "in_vectsize_index" : None,
                "out_vectsize_index" : None,
                "in_lanesize_index" : None,
                "out_lanesize_index" : None,
                "in_precision_index" : None,
                "out_precision_index" : None,
                "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
                "Signedness" : 1,
                "Cost" : "None",
                "SIMD" : "True",
                "Extensions" : "['integer_arith']",
            },
        },
        "semantics" : ['"(define (SCALAR  a )"','"a"'  ,'")"', '""'],
    },
}
