pim_extended_dsl ={
    "test_enum_1_comb_2_fused_pim_op_7": {
        "target_instructions": {
            "test_enum_1_comb_2_fused_pim_op_7": {
                "in_vectsize": 64,
                "out_vectsize": 64,
                "lanesize": 64,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "lanesize_index": 3,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "True",
                "Extensions": "[]",
                "args": [
                    "SYMBOLIC_BV_64",
                    "SYMBOLIC_BV_64",
                    "64",
                    "64",
                    "0",
                    "64",
                    "16",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_5_fused_pim_op_5": {
                "in_vectsize": 128,
                "out_vectsize": 128,
                "lanesize": 128,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "lanesize_index": 3,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "True",
                "Extensions": "[]",
                "args": [
                    "SYMBOLIC_BV_128",
                    "SYMBOLIC_BV_128",
                    "128",
                    "128",
                    "0",
                    "128",
                    "8",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_7_fused_pim_op_7": {
                "in_vectsize": 128,
                "out_vectsize": 128,
                "lanesize": 128,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "lanesize_index": 3,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "True",
                "Extensions": "[]",
                "args": [
                    "SYMBOLIC_BV_128",
                    "SYMBOLIC_BV_128",
                    "128",
                    "128",
                    "0",
                    "128",
                    "32",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_3_fused_pim_op_7": {
                "in_vectsize": 64,
                "out_vectsize": 64,
                "lanesize": 64,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "lanesize_index": 3,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "True",
                "Extensions": "[]",
                "args": [
                    "SYMBOLIC_BV_64",
                    "SYMBOLIC_BV_64",
                    "64",
                    "64",
                    "0",
                    "64",
                    "32",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_6_fused_pim_op_7": {
                "in_vectsize": 128,
                "out_vectsize": 128,
                "lanesize": 128,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "lanesize_index": 3,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "True",
                "Extensions": "[]",
                "args": [
                    "SYMBOLIC_BV_128",
                    "SYMBOLIC_BV_128",
                    "128",
                    "128",
                    "0",
                    "128",
                    "16",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_1_fused_pim_op_5": {
                "in_vectsize": 64,
                "out_vectsize": 64,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "lanesize_index": 3,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "True",
                "Extensions": "[]",
                "args": [
                    "SYMBOLIC_BV_64",
                    "SYMBOLIC_BV_64",
                    "64",
                    "64",
                    "0",
                    "64",
                    "8",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_5_fused_pim_op_5_extended_size_256_bw_8_ctx_0": {
                "in_vectsize": 256,
                "out_vectsize": 256,
                "lanesize": 256,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_256",
                    "SYMBOLIC_BV_256",
                    "256",
                    "256",
                    "0",
                    "256",
                    "8",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_6_fused_pim_op_7_extended_size_256_bw_16_ctx_0": {
                "in_vectsize": 256,
                "out_vectsize": 256,
                "lanesize": 256,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_256",
                    "SYMBOLIC_BV_256",
                    "256",
                    "256",
                    "0",
                    "256",
                    "16",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_7_fused_pim_op_7_extended_size_256_bw_32_ctx_0": {
                "in_vectsize": 256,
                "out_vectsize": 256,
                "lanesize": 256,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_256",
                    "SYMBOLIC_BV_256",
                    "256",
                    "256",
                    "0",
                    "256",
                    "32",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_5_fused_pim_op_5_extended_size_512_bw_8_ctx_0": {
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 512,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "512",
                    "512",
                    "0",
                    "512",
                    "8",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_6_fused_pim_op_7_extended_size_512_bw_16_ctx_0": {
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 512,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "512",
                    "512",
                    "0",
                    "512",
                    "16",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_7_fused_pim_op_7_extended_size_512_bw_32_ctx_0": {
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 512,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "512",
                    "512",
                    "0",
                    "512",
                    "32",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_5_fused_pim_op_5_extended_size_1024_bw_8_ctx_0": {
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 1024,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_1024",
                    "SYMBOLIC_BV_1024",
                    "1024",
                    "1024",
                    "0",
                    "1024",
                    "8",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_6_fused_pim_op_7_extended_size_1024_bw_16_ctx_0": {
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 1024,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_1024",
                    "SYMBOLIC_BV_1024",
                    "1024",
                    "1024",
                    "0",
                    "1024",
                    "16",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_7_fused_pim_op_7_extended_size_1024_bw_32_ctx_0": {
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 1024,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_1024",
                    "SYMBOLIC_BV_1024",
                    "1024",
                    "1024",
                    "0",
                    "1024",
                    "32",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_5_fused_pim_op_5_extended_size_2048_bw_8_ctx_0": {
                "in_vectsize": 2048,
                "out_vectsize": 2048,
                "lanesize": 2048,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_2048",
                    "SYMBOLIC_BV_2048",
                    "2048",
                    "2048",
                    "0",
                    "2048",
                    "8",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_6_fused_pim_op_7_extended_size_2048_bw_16_ctx_0": {
                "in_vectsize": 2048,
                "out_vectsize": 2048,
                "lanesize": 2048,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_2048",
                    "SYMBOLIC_BV_2048",
                    "2048",
                    "2048",
                    "0",
                    "2048",
                    "16",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_7_fused_pim_op_7_extended_size_2048_bw_32_ctx_0": {
                "in_vectsize": 2048,
                "out_vectsize": 2048,
                "lanesize": 2048,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_2048",
                    "SYMBOLIC_BV_2048",
                    "2048",
                    "2048",
                    "0",
                    "2048",
                    "32",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_5_fused_pim_op_5_extended_size_4096_bw_8_ctx_0": {
                "in_vectsize": 4096,
                "out_vectsize": 4096,
                "lanesize": 4096,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_4096",
                    "SYMBOLIC_BV_4096",
                    "4096",
                    "4096",
                    "0",
                    "4096",
                    "8",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_6_fused_pim_op_7_extended_size_4096_bw_16_ctx_0": {
                "in_vectsize": 4096,
                "out_vectsize": 4096,
                "lanesize": 4096,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_4096",
                    "SYMBOLIC_BV_4096",
                    "4096",
                    "4096",
                    "0",
                    "4096",
                    "16",
                    "-1",
                    "0"
                ]
            },
            "test_enum_1_comb_7_fused_pim_op_7_extended_size_4096_bw_32_ctx_0": {
                "in_vectsize": 4096,
                "out_vectsize": 4096,
                "lanesize": 4096,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "lanesize_index": None,
                "in_precision_index": 6,
                "out_precision_index": 6,
                "arg_permute_map": [
                    0,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1
                ],
                "Signedness": None,
                "Cost": "[]",
                "SIMD": "False",
                "Extensions": None,
                "args": [
                    "SYMBOLIC_BV_4096",
                    "SYMBOLIC_BV_4096",
                    "4096",
                    "4096",
                    "0",
                    "4096",
                    "32",
                    "-1",
                    "0"
                ]
            }
        },
        "semantics": [
            "\"(define (test_enum_1_comb_2_fused_pim_op_7  a b %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 )\"",
            "\"(define dst\"",
            "\"(apply\"",
            "\"concat\"",
            "\"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])\"",
            "\" (apply\"",
            "\" concat\"",
            "\" (for/list ([idx0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])\"",
            "\"  (define %lastidx0 (-  %elemsize0  1))\"",
            "\"  (define %6 (+  idx0.new  %lastidx0))\"",
            "\"  (define %7 (extract  %6 idx0.new a))\"",
            "\"  (define %9 (extract  %6 idx0.new b))\"",
            "\"  (define %10.ab0 (bvaddnw %7 %9 %elemsize0 %arg0 ))\"",
            "\"  %10.ab0\"",
            "\" )\"",
            "\" )\"",
            "\")\"",
            "\")\"",
            "\")\"",
            "\"(bvpadhighbits  dst %arg1)\"",
            "\")\"",
            "\"\""
        ]
    }
}
